name: Test Calculator
on:
  push:
    branches:
      - main
jobs:
  test_calculator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          pip3 install -r code/python/requirements.txt
      - name: Run linters
        run: |
          flake8 code/python
      - name: Run tests
        run: |
          pytest -m unittest discover -s code/python -p "test_*.py"
      - name: Run Security checks
        run: |
          bandit -r code/python
