name: Label - Advice
on:
  label:
    types: [created]
    branches:
      - 'main'
    labels:
      - 'python'

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: echo "La etiqueta que acabas de crear se llama: ${{ github.event.label.name }}"
