name: Second_action_joel
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: echo "Bye world!"
  
  bye-world:
    runs-on: ubuntu-latest
    needs: hello-world

    steps:
      - name: First step
        run: echo "Hello world!"
      - name: Second step
        run: echo "Bye world!"